"""Stable public facade for the Forge Runtime.

Use the package root for the chat/session contract. Workflow, tool, plugin and
FastAPI integrations live in their dedicated subpackages. Implementation
modules remain importable because this is Python, but they are not supported
API unless documented here or in one of those subpackages.
"""

from kbws_forge_runtime.errors import (
    AgentNotFoundError,
    ForgeRuntimeError,
    IllegalParameterError,
    RunBudgetExceededError,
    RunCancelledError,
    RunError,
    RunTimeoutError,
    RunUsageUnavailableError,
    SessionNotFoundError,
    SessionOwnerError,
    ToolApprovalRequiredError,
    ToolNotAllowedError,
)
from kbws_forge_runtime.evals import (
    EvalCase,
    EvalCaseResult,
    EvalRun,
    EvalRunner,
    EvalStatus,
    EvalStore,
    EvalSuite,
    Grader,
    GraderCaseResult,
    GraderResult,
    contains,
    exact,
    json_schema,
    llm_judge,
    load_eval_suites,
    regex,
    tool_trajectory,
)
from kbws_forge_runtime.execution import (
    ModelExecutor,
    ModelUsage,
    RunContext,
    RunPolicy,
    ToolApprovalHandler,
    ToolApprovalRequest,
    ToolExecutor,
    ToolPolicy,
    UsageResolver,
)
from kbws_forge_runtime.models import (
    AgentInfo,
    ChatEvent,
    ChatMessage,
    ChatPart,
    ChatRequest,
    ChatResult,
    FilePart,
    InlineDataPart,
    MessageCreated,
    ModelFailed,
    ModelFinished,
    ModelStarted,
    RunCancelled,
    RunFailed,
    RunFinished,
    RunStarted,
    TextDelta,
    TextPart,
    ToolFailed,
    ToolFinished,
    ToolStarted,
    UserSession,
)
from kbws_forge_runtime.runtime import AgentRuntime
from kbws_forge_runtime.sinks import EventSink, InMemoryEventSink

__all__ = [
    "AgentInfo",
    "AgentNotFoundError",
    "AgentRuntime",
    "ChatEvent",
    "ChatMessage",
    "ChatPart",
    "ChatRequest",
    "ChatResult",
    "EventSink",
    "EvalCase",
    "EvalCaseResult",
    "EvalRun",
    "EvalRunner",
    "EvalStatus",
    "EvalStore",
    "EvalSuite",
    "FilePart",
    "ForgeRuntimeError",
    "Grader",
    "GraderCaseResult",
    "GraderResult",
    "IllegalParameterError",
    "InMemoryEventSink",
    "InlineDataPart",
    "MessageCreated",
    "ModelExecutor",
    "ModelFailed",
    "ModelFinished",
    "ModelStarted",
    "ModelUsage",
    "RunBudgetExceededError",
    "RunCancelled",
    "RunCancelledError",
    "RunContext",
    "RunError",
    "RunFailed",
    "RunFinished",
    "RunStarted",
    "RunPolicy",
    "RunTimeoutError",
    "RunUsageUnavailableError",
    "SessionNotFoundError",
    "SessionOwnerError",
    "TextDelta",
    "TextPart",
    "ToolApprovalHandler",
    "ToolApprovalRequest",
    "ToolApprovalRequiredError",
    "ToolExecutor",
    "ToolFailed",
    "ToolFinished",
    "ToolNotAllowedError",
    "ToolPolicy",
    "ToolStarted",
    "UsageResolver",
    "UserSession",
    "contains",
    "exact",
    "json_schema",
    "llm_judge",
    "load_eval_suites",
    "regex",
    "tool_trajectory",
]
